import { Inter } from "next/font/google";
import "./globals.css";
import Themeprovider from "./_providers/themeprovider";
import Queryprovider from "./_providers/queryprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Themeprovider>
      <Queryprovider>{children}</Queryprovider>
      
    </Themeprovider>
  );
}
