import { Inter } from "next/font/google";
import "./globals.css";
import Themeprovider from "./_providers/themeprovider";
import Queryprovider from "./_providers/queryprovider";
import Hero from "../app/components/navbar"
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Themeprovider>
   
      <Queryprovider> <Hero><Footer>{children}</Footer></Hero></Queryprovider>
      
    </Themeprovider>
  );
}
